### ISSUE TITLE
«Could not find 'mime-types' (< 4.0, >= 1.16) among 260 total gem(s)»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [discourse-pro/df-core#5]
```
I, [2018-04-08T03:41:03.839004 #14]  INFO -- : > cd /var/www/discourse && su discourse -c 'bu           ndle exec rake db:migrate'
rake aborted!
Gem::MissingSpecError: Could not find 'mime-types' (< 4.0, >= 1.16) among 260 total gem(s)
Checked in 'GEM_PATH=/var/www/discourse/vendor/bundle/ruby/2.4.0', execute `gem env` for more            information
/var/www/discourse/lib/plugin_gem.rb:18:in `load'
/var/www/discourse/lib/plugin/instance.rb:488:in `gem'
/var/www/discourse/plugins/df-core/plugin.rb:43:in `activate!'
/var/www/discourse/lib/plugin/instance.rb:433:in `instance_eval'
/var/www/discourse/lib/plugin/instance.rb:433:in `activate!'
/var/www/discourse/lib/discourse.rb:151:in `block in activate_plugins!'
/var/www/discourse/lib/discourse.rb:148:in `each'
/var/www/discourse/lib/discourse.rb:148:in `activate_plugins!'
/var/www/discourse/config/application.rb:202:in `<class:Application>'
/var/www/discourse/config/application.rb:28:in `<module:Discourse>'
/var/www/discourse/config/application.rb:27:in `<top (required)>'
/var/www/discourse/Rakefile:5:in `require'
/var/www/discourse/Rakefile:5:in `<top (required)>'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>
```

**Comment by dmitrii-fediuk** [comment]
Fixed in [1.4.0](https://github.com/discourse-pro/df-core/releases/tag/1.4.0).
